FROM node:14-alpine AS builder

ENV NODE_ENV production

# Add a work directory
WORKDIR /app

# Copy dependencies files
COPY src/package.json .
COPY src/package-lock.json .

# Install dependencies
RUN yarn install --production

# Copy app files
COPY src/ .

# Build the app
RUN yarn build

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production

# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
