version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /qrsec/db:/data/db
      - /qrsec/configdb:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8880:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${DB_SERVER}
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_ADMIN_PASSWORD}
    restart: unless-stopped
    links:
      - mongodb

