services:

# ---     Mongodb     ---

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /home/lucas/mongo_db/qrsec/db:/data/db                  # Change in prod
      - /home/lucas/mongo_db/qrsec/configdb:/data/configdb      # Change in prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  mongo_express:                                                # Remove in prod
    image: mongo-express:1.0.2
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - 8880:8081
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${DB_SERVER}
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_ADMIN_PASSWORD}

# ---     Backend     ---

  backend:
    image: qrsec_backend:${BACKEND_VERSION}
    build:
      context: ../../qrsec_backend
      dockerfile: ./Dockerfile
      tags:
        - 'qrsec_backend:${BACKEND_VERSION}'
        - 'qrsec_backend:latest'
    container_name: qrsec_backend
    restart: unless-stopped
    links:
      - mongodb
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT}

      - API_PATH=${API_PATH}
      - API_PATH_INVITES=${API_PATH_INVITES}
      - API_PATH_PUBLIC_INVITES=${API_PATH_PUBLIC_INVITES}
      - API_PATH_GUESTS=${API_PATH_GUESTS}
      - API_PATH_USERS=${API_PATH_USERS}
      - API_PATH_ADDRESSES=${API_PATH_ADDRESSES}

      - SPRINGDOC_API_DOCS_PATH=${SPRINGDOC_API_DOCS_PATH}
      - SPRINGDOC_SWAGGER_UI_PATH=${SPRINGDOC_SWAGGER_UI_PATH}
      - SPRINGDOC_SWAGGER_UI_ENABLED=${SPRINGDOC_SWAGGER_UI_ENABLED}
      - SPRINGDOC_SWAGGER_UI_OPERATIONSSORTER=${SPRINGDOC_SWAGGER_UI_OPERATIONSSORTER}
      - SPRINGDOC_SWAGGER_UI_TAGSSORTER=${SPRINGDOC_SWAGGER_UI_TAGSSORTER}

      - MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT=${MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT}
      - MANAGEMENT_ENDPOINT_INFO_ENABLED=${MANAGEMENT_ENDPOINT_INFO_ENABLED}
      - MANAGEMENT_ENDPOINT_HEALTH_ENABLED=${MANAGEMENT_ENDPOINT_HEALTH_ENABLED}
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED}
      - MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED=${MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED}
      - SPRING_DATA_REST_DETECTION_STRATEGY=${SPRING_DATA_REST_DETECTION_STRATEGY}
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}

      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS}
      - CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}

      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      - SPRING_DATA_MONGODB_USERNAME=${SPRING_DATA_MONGODB_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${SPRING_DATA_MONGODB_PASSWORD}
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
      - SPRING_DATA_MONGODB_PORT=${SPRING_DATA_MONGODB_PORT}
      - SPRING_DATA_MONGODB_HOST=${SPRING_DATA_MONGODB_HOST}
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION}

# ---     Frontend     ---

  frontend:
    image: qrsec_frontend:${FRONTEND_VERSION}
    build:
      context: ../../qrsec_frontend
      dockerfile: ./Dockerfile
      tags:
        - 'qrsec_frontend:${FRONTEND_VERSION}'
        - 'qrsec_frontend:latest'
      args:
        - REACT_APP_WHOLE_FRONTEND_BASE=${REACT_APP_WHOLE_FRONTEND_BASE}
        - REACT_APP_WHOLE_BACKEND_BASE=${REACT_APP_WHOLE_BACKEND_BASE}
        - REACT_APP_MAPS_API=${REACT_APP_MAPS_API}
        - REACT_APP_GOOGLE_OAUTH_CLIENT_ID=${REACT_APP_GOOGLE_OAUTH_CLIENT_ID}
    container_name: qrsec_frontend
    restart: unless-stopped
    links:
      - backend
    environment:
      - REACT_APP_WHOLE_FRONTEND_BASE=${REACT_APP_WHOLE_FRONTEND_BASE}
      - REACT_APP_WHOLE_BACKEND_BASE=${REACT_APP_WHOLE_BACKEND_BASE}
      - REACT_APP_MAPS_API=${REACT_APP_MAPS_API}
      - REACT_APP_GOOGLE_OAUTH_CLIENT_ID=${REACT_APP_GOOGLE_OAUTH_CLIENT_ID}

# ---     Cloudflare Tunnel     ---

  cloudflare_tunnel:
    image: cloudflare/cloudflared:2024.9.1
    container_name: cloudflare-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run

# ---     Reverse proxy     ---

  reverse_proxy:
    image: nginx:alpine3.19
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - backend
      - frontend
      - mongodb
      - cloudflare_tunnel
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
